# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gkeemailing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
        -
          name: mailing
          image: 'gcr.io/XXXXXXXX/gkeemailing:latest'
          ports:
            -
              containerPort: 8080
          env:
            -
              name: PORT
              value: '8080'
            -
              name: SG_API_KEY
              valueFrom: 
                secretKeyRef: 
                    name: mail-secret
                    key: apikey
